language: cpp
dist: bionic
sudo: required
only:
  - master
  - develop
  - \/feature\/.+
  - \/fix\/.+
  - \/hotfix\/.+
  - \/release\/.+

addons:
  apt:
    sources:
    - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
    - cppcheck
    - cmake
    - make
    - automake
    - sqlite3
before_install:
  - sudo apt-get update && sudo apt-get install libsqlite3-dev libssl1.0-dev libssl1.0.0 libusb-1.0-0-dev libudev-dev libgtest-dev libbluetooth3 libbluetooth-dev bluez-tools libpulse-dev python3-pip python3-setuptools
  - sudo apt-get install -f clang-format-6.0

script:
  - cppcheck --enable=all --inconclusive --suppress=missingInclude --inline-suppr -i "src/3rd_party-static" -i "src/3rd_party" --quiet --error-exitcode=1 src
  - ./tools/infrastructure/check_style.sh
  - mkdir build && cd build
  - cmake ../ -DBUILD_TESTS=ON
  - make install-3rd_party && make -j `nproc` install && sudo ldconfig && make test
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - CTEST_OUTPUT_ON_FAILURE=TRUE
  - LD_LIBRARY_PATH=.
